### ISSUE TITLE
Navigation buttons and status bar stuck on screen

### ISSUE THREAD

**Issue by chubritsa** [jmir1/aniyomi#266] opened 2021-11-30 15:22 UTC
### Steps to reproduce

When I'm in the video player and then select the quality of the video the navigation buttons and status bar get stuck. Only way i know to remove them is to close and open the player. 
![Screenshot_2021-11-30-17-11-11-397_xyz jmir tachiyomi mi](https://user-images.githubusercontent.com/95298968/144075057-6bcdaf53-fa6f-4ba2-9b07-67f4ca888fda.jpg)

### Expected behavior

Nav buttons and status bar should go away

### Actual behavior

They dont go away

### Aniyomi version

v0.12.3.5

### Android version

Android 9

### Device

Xiaomi Redmi S2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment] 2021-11-30 15:40
duplicate of #199

**Closed by jmir1** 2021-11-30 15:40 UTC
