### ISSUE TITLE
Erorr getting links

### ISSUE THREAD

**Issue by Hellokittymaster09** [jmir1/aniyomi#376] opened 2022-02-01 07:48 UTC
### Steps to reproduce

I try to open any anime titles and I would get an error message saying " error getting links " 
I tried everything to restart the app, uninstall and install again the extensions, uninstalled the app, updated the app and I still get the problem

### Expected behavior

Episode should play

### Actual behavior

Video dosen't play and gets " error getting links "
text

![Screenshot_20220201-094125_Aniyomi](https://user-images.githubusercontent.com/98802344/151930118-8bb268e9-8dc3-4514-8111-c76f526899d7.jpg)

### Aniyomi version

0.12.3.6

### Android version

Android 9

### Device

Samsung galaxy j5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by raeespulikkal** [comment] 2022-02-02 03:35
Try downloading other extensions and see if they play the anime you want. If it does then click on the three dots in top corner and migrate the anime to that extention. And once the issue is solved you can migrate it back to animepahe

**Comment by glokta1** [comment] 2022-02-05 17:56
Please search for existing issues before making a new, duplicate one. see #366. You can close this now @jmir1

**Closed** 2022-02-05 17:57 UTC
