### ISSUE TITLE
Player doesn't occupy whole screen

### ISSUE THREAD

**Issue by SanOtaku09** [jmir1/aniyomi#283] opened 2021-12-15 06:01 UTC
### Steps to reproduce

![Screenshot_2021-12-15-06-23-51-785_xyz jmir tachiyomi mi debug](https://user-images.githubusercontent.com/92387092/146131361-44676ad7-17e6-455a-b225-3766b61a1b32.jpg)

That white line in left side of picture is what I'm talking about

### Expected behavior

Should occupy whole screen like MX player

### Actual behavior

Bold white line in the left hand side of display

### Aniyomi version

Preview r4403

### Android version

Android 11

### Device

Redmi note 10 s

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment] 2021-12-15 18:19
duplicate of #199

**Closed by jmir1** 2021-12-15 18:19 UTC
