### ISSUE TITLE
Aniyomi video player 

### ISSUE THREAD

**Issue by Samy20023** [jmir1/aniyomi#250] opened 2021-11-26 14:09 UTC
When I open the anime to watch in app video player the status bar shown can you fix it to be a full screen experience .

![Screenshot_20211126-161140_Aniyomi.jpg](https://user-images.githubusercontent.com/88319767/143593651-69052caf-5271-48b0-9a59-21a28bb57b41.jpg)

**Comment by jmir1** [comment] 2021-11-26 14:28
duplicate of #199

**Closed by jmir1** 2021-11-26 14:28 UTC
