### ISSUE TITLE
Add us to the novels section

### ISSUE THREAD

**Issue by yemenihandsome** [jmir1/aniyomi#394] opened 2022-02-12 06:41 UTC
### Describe your suggested feature

It should contain three sections (Anime section, Manga section, Novels section)

### Other details

Do you have the possibility to add the novels section?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Aceiow** [comment] 2022-02-18 11:01
### Use Animekisa
They have added Animekisa . There are .tv and .in . tv scrapes from gogo and .in scrapes from 9anime afaik . The version that we have is .in so you can say we have 9anime . Just give it a try .

**Comment by Aceiow** [comment] 2022-02-18 11:08
### Check out this
[Tachiyomi Faq](https://tachiyomi.org/help/faq/#can-tachiyomi-read-light-novels)
Aniyomi is based on tachiyomi with the anime support . If they add novel support it will be great then the dev have to focus on both anime and novel . Until then you can try [this](https://github.com/LNReader/lnreader) maybe its based on tachiyomi .

**Comment by jmir1** [comment] 2022-03-02 12:44
duplicate of #70

**Closed by jmir1** 2022-03-02 12:44 UTC
