### ISSUE TITLE
Navigation bar not hide in internal player

### ISSUE THREAD

**Issue by AyAt786M** [jmir1/aniyomi#199] opened 2021-10-19 06:05 UTC
Steps to reproduce

1. Search any anime.
2. Play it in internal player.

### Expected behavior

Navigation bar should hide while paying anime in internal player.

![Screenshot_2021-10-19-09-45-52-543](https://user-images.githubusercontent.com/88781092/137852447-837fb9e7-d369-4ecb-a794-c68cd4bdf61b.jpeg)
                                           ⬆️                      ⬆️                         ⬆️

### Actual behavior

It's not hide navigation bar in internal player.

![Screenshot_2021-10-19-11-27-33-828](https://user-images.githubusercontent.com/88781092/137852631-78abea2f-cb8c-4962-b035-fb36eef198f7.jpeg)
                                           ⬆️                      ⬆️                         ⬆️

### Aniyomi version

12.3.2 and r4253

### Android version

7.0

### Device

Lenovo TB-7304F

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.2](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Vignesh-Vin** [comment] 2021-11-23 09:46
I'm facing the same issue.

Android 11

**Comment by Vignesh-Vin** [comment] 2021-11-23 10:17
My issue is the same but with the notification bar.

Notification bar is hidden the first time you launch the player, if you touch any button then it shows up and doesn't hide again.

Device: Mi A3
Android 11 (Evolution X ROM)

But the issue doesn't exist in v0.12.3.3 (currently using it)

**Comment by Grafcube** [comment] 2021-11-27 06:04
I am also having this issue. When I first play an episode it's fine, but if I open the settings menu (playback speed and video quality) it causes the notification bar to remain visible (player becomes smaller). This also happens when I go into Picture in Picture mode and then return to the app.

Going back and reopening the episode fixes this but it can happen again in the same way.

**Comment by kaladin-syl** [comment] 2021-11-27 09:21
@jmir1 Hi, I would like to work on this issue :)

**Comment by jmir1** [comment] 2021-11-27 10:06
> @jmir1 Hi, I would like to work on this issue :)

Feel free to do so! I sadly can't reproduce this bug. On my devices, the nav bar stays hidden.

**Comment by noxan-dev** [comment] 2021-11-28 00:21
Just want to leave this here, it seems similar. The status bar doesn't go away for me when I go back to fullscreen from PiP.

**Comment by MHMEDxAHMED** [comment] 2021-11-28 17:46
> @jmir1 Hi, I would like to work on this issue :)

If so iam willing to help

**Comment by MHMEDxAHMED** [comment] 2021-11-28 17:49
I have the same issue with notification bar whenever I touch any element of the player screen 
My manhua categorization is now close to 600 manhua with 34 categories but I can test for you any time

**Comment by MHMEDxAHMED** [comment] 2021-11-28 17:51
Mu device is 
samsung s9 plus 
Android 10
One ui 2.5 interface

**Comment by sawzaw78** [comment] 2021-12-03 21:54
I was able to fix this by going to Settings > Advanced > Tablet Player > Landscape

**Comment by Grafcube** [comment] 2021-12-04 02:04
Unfortunately this doesn't work for me. I am using a Nokia 6.1.

**Comment by glokta1** [comment] 2021-12-05 06:58
I think I've found the problem. See the Activity Lifecycle flowchart:

![image](https://user-images.githubusercontent.com/71697384/144736478-a532c6cb-7f7c-4ed5-904c-1968c367f8b5.png)

The problem lies in where the `setVisibilities()` function is called in `PlayerActivity.kt`.  Currently, it's inside the `onCreate()` method. The UI flags for hiding the system bars clear when the user temporarily clicks away from the video player (for example by clicking the settings button or by switching to a different application). 

`onPause()` is called when the settings button is pressed.

`onStop()` is called when we switch/exit the application.

When the user returns to the application, the system does NOT call `onCreate()` where these UI flags lie. Moving it to `onResume()` should fix it.

I'm trying to make it work on my system but it's very slow with Android Studio so if someone wants to carry the torch from here, feel free to do so and report back

**Comment by jmir1** [comment] 2021-12-05 19:56
@glokta1 Thanks for the helpful comment! I will look into it when I get the time and update you.

**Comment by jmir1** [comment] 2022-01-06 02:56
closed by b526b6dbe2d0de4d8c33220f1e5dd2e822964616

**Closed by jmir1** 2022-01-06 02:56 UTC
