### ISSUE TITLE
Mpv doesn't appear in the list of external players

### ISSUE THREAD

**Issue by M71Z** [jmir1/aniyomi#235] opened 2021-11-21 23:20 UTC
### Steps to reproduce

Install mpv
Toggle external players in settings
Choose an episode

### Expected behavior

[Mpv](https://github.com/mpv-android/mpv-android/releases) should be found in the list of media players shown

### Actual behavior

Only vlc, mx player and few others.. Why?

### Crash logs

No crashes

### Aniyomi version

0.12.3.3

### Android version

Android 11

### Device

Xiaomi Redmi Note 8 Pro

### Other details

https://user-images.githubusercontent.com/85505634/142782854-09266e0c-c57a-48f5-ac5c-a5d3a89bf2da.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.3](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment] 2021-11-22 14:39
Not a bug, MPV just isn't supported yet.
Can be added though.

**Comment by AbdullahMehiz** [comment] 2021-11-22 14:44
> Not a bug, MPV just isn't supported yet. Can be added though.

May i ask how can i add it?

**Comment by jmir1** [comment] 2021-11-22 14:49
Sorry, I reread your issue, I misunderstood at first. I thought you meant in the settings where you can choose your default external player.

If you have no default external player set, your OS should let you choose MPV.

It works fine on my device.

What OS are you running?

**Comment by AbdullahMehiz** [comment] 2021-11-22 14:56
MIUI 12.5.5 Global
I even tried making mpv the default for playing videos but still nothing changed
![Screenshot_2021-11-22-15-55-04-600_com android settings](https://user-images.githubusercontent.com/85505634/142883262-fd369201-c38a-41a4-b86e-df52739cd5ef.jpg)

**Comment by jmir1** [comment] 2021-11-22 14:58
OK I searched online about it and found a similar issue: https://stackoverflow.com/questions/49973738/implicit-intents-not-showing-all-available-options
Not sure what's causing it or how to fix yet, but I will investigate further later

**Comment by AbdullahMehiz** [comment] 2021-11-23 22:37
Sooo, i've discovered something
This issue actually happens on only 2 sources and the local source...
Mpv does appear on almost every source except Genoanime and Haho.moe and local source.
Also, when i tried doing this animepahe, the app kept crashing
Here are the crash logs https://pastebin.com/yHBE7Sv6
![Screenshot_2021-11-23-23-23-49-355_android](https://user-images.githubusercontent.com/85505634/143139335-84c75921-b7cb-4e8d-822c-f31244ca82f8.jpg)

**Comment by jmir1** [comment] 2021-11-24 01:51
thanks for the new insights!
the crash should be fixed with this: f903c0c32084650d4b96941639115807f73252be
and i pushed this: b86ac85c7a5c784f1e89969732373feabdcbb615 which uses the proper mime type so we'll see if that fixes your issue

**Comment by jmir1** [comment] 2021-11-25 00:53
https://github.com/jmir1/aniyomi-preview/releases/tag/r4368
can you try it with the new preview version? let me know if it improved something

**Comment by AbdullahMehiz** [comment] 2021-11-25 09:48
For some reason, after the update, the app automatically chooses VLC (https://streamable.com/4am1hr) to play episodes on the local source. When i uninstalled Vlc, the app started crashing(https://streamable.com/a8bhd3).
Here are the crash logs: https://pastebin.com/QE5tdfKN

**Comment by jmir1** [comment] 2021-11-25 10:40
> automatically chooses VLC
I'm pretty sure you have set VLC as your preference in the settings. Please check settings > player > external player preference and make sure it is set to None

**Comment by AbdullahMehiz** [comment] 2021-11-25 10:41
It is set to none, i haven't changed this option when i installed the app...
![Uploading Screenshot_2021-11-25-11-41-01-319_xyz.jmir.tachiyomi.mi.debug.jpg…]()

**Comment by AbdullahMehiz** [comment] 2021-11-25 11:01
I recorded the stuff https://streamable.com/8o16im

**Comment by jmir1** [comment] 2021-11-25 11:22
ok i think finally fixed it with this: 5f75512a2e1eefc3d7ee46966c3ecf6c01d0cfe0
update for the preview should be ready in about 10 minutes, then you can try again

**Comment by jmir1** [comment] 2021-11-25 11:23
i used `application/x-matroska` instead of `video/x-matroska` nad only vlc could handle that so it chose that app per default

**Comment by Morrisuzumaki** [comment] 2021-11-25 11:25
Hey 👋 I need  a lil bit of help here , Everytime I try to download aniyomi
it says I need authorization

**Comment by AbdullahMehiz** [comment] 2021-11-25 11:34
It fixed the crashing, but mpv still isn't appearing:'(

**Comment by jmir1** [comment] 2021-11-25 11:37
sad.

**Comment by erickyun** [comment] 2021-12-07 14:55
@jmir1
Hi,

with the kodi android app users can set up mpv-android as an external player with creating a  `playercorefactory.xml` file.
users need to create an extra playercorefactory.xml file inside their userdata folder(`Android/data/org.xbmc.kodi/files/.kodi/userdata/`) and then mpv does appear as external player can not the same thing be done with aniyomi?

[playercorefactory.zip](https://github.com/jmir1/aniyomi/files/7669203/playercorefactory.zip)

**Comment by M71Z** [comment] 2022-01-18 04:57
I think this should be closed

**Closed** 2022-01-18 04:58 UTC
