### ISSUE TITLE
ANIME EPISODE SIZE IS NOT SHOWING

### ISSUE THREAD

**Issue by Adi432144** [jmir1/aniyomi#548] opened 2022-04-25 08:11 UTC
![20220425_132513](https://user-images.githubusercontent.com/74503284/165047724-5ec80768-b8b0-49bb-9724-b26175e5d887.png)
### Describe your suggested feature

I like your app very very much because your app make easy to download or watch anime but 1 thing is make me uncomfortable with your app is anime episode size is not showing
Think a with less internet left, he wants to download Anime episode and do other things , if episode required more internet than the left internet he will not able to anything.
They are many user with condition using your app
So please make sure that you make features that show size of episode

### Other details

I want to say that It is not showing episode size create trouble for users who is using your app 
Example
If a user wants to download Anime episode in your app in 720p he thinks episode size is approx 600mb so he saved that much amount of internet for the episode but he started downloading the episode after sometime 100% internet used is pop when he checked only 50% of episode is downloaded so his internet is wasted
So please make sure that you make features that show size of episode

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Lukyzzz** [comment] 2022-04-28 00:01
Duplicate of the https://github.com/jmir1/aniyomi/issues/238#issue-1060698472

**Closed** 2022-05-03 12:29 UTC
