### ISSUE TITLE
Quality download option

### ISSUE THREAD

**Issue by bleedout6840** [jmir1/aniyomi#219] opened 2021-11-11 18:40 UTC
### Describe your suggested feature

When you download it should ask which quality and  in settings I should have and option like always download in 360p or 480p 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.1](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by jmir1** [comment] 2021-11-13 03:35
duplicate of #154

**Closed by jmir1** 2021-11-13 03:35 UTC
