### ISSUE TITLE
A Desktop Release

### ISSUE THREAD

**Issue by piyushsingariya** [jmir1/aniyomi#717] opened 2022-08-11 05:26 UTC
### Describe your suggested feature

AniYomi Should have a desktop release as well. I have seen online forums talking and asking for such an application

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Samfun75** [comment] 2022-08-11 11:04
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

Did you really?

**Comment by lasersPew** [comment] 2022-08-12 09:48
I would like to make a petition to close this issue.

# Why?:
## 1. There will be no desktop-native Aniyomi. 
If you want to have one, create it yourself. [Tachidesk](https://github.com/Suwayomi/Tachidesk-Server) also exists if you want a Tachiyomi without anime but guessing the issue you want a Tachiyomi with anime on Desktop, please move to the next section.

## 2. You can run Aniyomi in a Android Emulator. Use them.
There are a shit ton of Android Emulators in existence. Even Windows Subsystem for Android exists. [Set one up](https://www.xda-developers.com/how-to-run-android-apps-on-any-windows-11-pc/) and get adb and a Aniyomi apk (x86 or x86-64 for WSA* and arm64 or armv7 for other emulators) from [releases](https://github.com/jmir1/aniyomi/releases/tag/v0.12.3.7). From there, you can sideload apps using this [guide](https://www.windowscentral.com/how-sideload-android-apps-using-wsa-windows-11) for WSA or double click the apk in explorer for other emulators. After that, you can copy a backup from Aniyomi, install extensions and log into trackers, and done. You can now use Aniyomi on desktop.

*You can choose x86 or arm since doesn't matter in WSA given that you have a x86 chip(from Intel or AMD) since it has ARM translation engine that fully works though I recommend going with the x86 version(if you have Intel or AMD CPU) or ARM version(for other emulators or if you have a ARM CPU)since some operations introduce overhead and hardware may not be fully utilized if host architecture isn't the app architecture including hardware acceleration which is vital for video decoding(or playing video).

## 3. This is the third duplicate of a desktop app issue.
The other issues are #147 #560 and #637

**Closed** 2022-08-14 03:04 UTC
