### ISSUE TITLE
Anime Download Issue

### ISSUE THREAD

**Issue by Luffy12912** [jmir1/aniyomi#412] opened 2022-02-22 11:44 UTC
### Steps to reproduce

1. Open anime from any extensions.
2. Click on download button wait 2 sec.
3. It will stop downloading automatically and won't give any error message.

### Expected behavior

Episode should be downloaded

### Actual behavior

![IMG_20220222_171124](https://user-images.githubusercontent.com/100204458/155125692-ee414428-b6de-46fb-aeba-212006d54420.jpg)

### Aniyomi version

App version: 0.12.3.6

### Android version

Android 10

### Device

Poco X2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.5](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Eximinati** [comment] 2022-02-22 19:32
I am getting same issue with other extensions amd zoro.to extension is not working at all...

**Comment by vehosah** [comment] 2022-03-04 12:34
> I am getting same issue with other extensions amd zoro.to extension is not working at all...

And Im getting in on 9anime and geno

**Comment by suhan-paradkar** [comment] 2022-03-10 03:47
Try switching the quality of the video....
Go to `Browse> Anime extensions> 'Extension Settings'` Press the gear icon and set the video quality....
Some anime providers don't have 1080p quality...
I personally prefer 480p.. since it uses less data and has enough clarity..

**Comment by jmir1** [comment] 2022-04-01 12:46
im pretty sure i found the cause of this bug.
ffmpeg doesnt work well with commas in the http header options.
i will fix this in the next update.
maybe the extensions will also be updated to fix this.

**Comment by jmir1** [comment] 2022-04-01 19:28
fixed by 98b7e1dbebb9460a7a036f3c738772be9121b6fa

**Closed by jmir1** 2022-04-01 19:28 UTC
Labels: bug
